#include "../../include/core/types_binding.h"

KS_API ks_no_ret ks_types_lua_bind(Ks_Script_Ctx ctx) {
    ks_script_register_enum(ctx, "types",
        KS_SCRIPT_ENUM_MEMBER("UNKNOWN", KS_TYPE_UNKNOWN),
        KS_SCRIPT_ENUM_MEMBER("NIL", KS_TYPE_NIL),
        KS_SCRIPT_ENUM_MEMBER("VOID", KS_TYPE_VOID),
        KS_SCRIPT_ENUM_MEMBER("BOOL", KS_TYPE_BOOL),
        KS_SCRIPT_ENUM_MEMBER("CHAR", KS_TYPE_CHAR),
        KS_SCRIPT_ENUM_MEMBER("INT", KS_TYPE_INT),
        KS_SCRIPT_ENUM_MEMBER("UINT", KS_TYPE_UINT),
        KS_SCRIPT_ENUM_MEMBER("FLOAT", KS_TYPE_FLOAT),
        KS_SCRIPT_ENUM_MEMBER("DOUBLE", KS_TYPE_DOUBLE),
        KS_SCRIPT_ENUM_MEMBER("CSTRING", KS_TYPE_CSTRING),
        KS_SCRIPT_ENUM_MEMBER("PTR", KS_TYPE_PTR),
        KS_SCRIPT_ENUM_MEMBER("USERDATA", KS_TYPE_USERDATA),
        KS_SCRIPT_ENUM_MEMBER("LIGHTUSERDATA", KS_TYPE_LIGHTUSERDATA),
        KS_SCRIPT_ENUM_MEMBER("TABLE", KS_TYPE_SCRIPT_TABLE),
        KS_SCRIPT_ENUM_MEMBER("FUNCTION", KS_TYPE_SCRIPT_FUNCTION),
        KS_SCRIPT_ENUM_MEMBER("COROUTINE", KS_TYPE_SCRIPT_COROUTINE),
        KS_SCRIPT_ENUM_MEMBER("ANY", KS_TYPE_SCRIPT_ANY)
    );
}