local function setupVcpkg()
    local vcpkg_root = os.getenv("VCPKG_ROOT")
    if not vcpkg_root then return false end
    
    local triplet = os.target() == "windows" and "x64-windows" 
                  or os.target() == "linux" and "x64-linux" 
                  or "x64-osx"
    
    return {
        includedirs = { path.join(vcpkg_root, "installed", triplet, "include") },
        libdirs = { path.join(vcpkg_root, "installed", triplet, "lib") }
    }
end

vcpkg = setupVcpkg()

workspace "Keystone-Engine"
    configurations { "Debug", "Release" }
    platforms { "x64" }
    startproject "KeyStone-CLI"

    include "./KeyStoneCore/premake5.lua"
    include "./KeyStoneCLI/premake5.lua"

newaction {
    trigger = "init",
    description = "Create build directory structure",
    execute = function()
        print("Creating build directory structure...")
        os.mkdir("build/bin/Debug")
        os.mkdir("build/bin/Release")
        os.mkdir("build/obj/Debug")
        os.mkdir("build/obj/Release")
        print("Directory structure created!")
    end
}

newaction {
    trigger = "clean",
    description = "Remove all files generated by premake and build directories.",
    execute = function()
        print("Removing build dir...")
        os.rmdir("build")
        local sln_ext = "*.sln"
        local vcxproj_ext = "*.vcxproj"
        local vcxproj_user = "*.vcxproj.user"
        local vcxproj_filters = "*.vcxproj.filters"

        if os.istarget("windows") then
            print("Removing Visual Studio files...")
            os.execute("forfiles /S /M " .. sln_ext .. " /C \"cmd /c del @path\"")
            os.execute("forfiles /S /M " .. vcxproj_ext .. " /C \"cmd /c del @path\"")
            os.execute("forfiles /S /M " .. vcxproj_filters .. " /C \"cmd /c del @path\"")
            os.execute("forfiles /S /M " .. vcxproj_user .. " /C \"cmd /c del @path\"")
        else
            -- Per Linux/macOS, il comando "find" è l'ideale.
            print("Removing Visual Studio files...")
            os.execute("find . -name " .. sln_ext .. " -type f -delete")
            os.execute("find . -name " .. vcxproj_ext .. " -type f -delete")
            os.execute("find . -name " .. vcxproj_filters .. " -type f -delete")
            os.execute("find . -name " .. vcxproj_user .. " -type f -delete")
        end
        print("Clean Completed!")
    end
}